version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 8
  labels:
  - javascript
  ignore:
  - dependency-name: i18next
    versions:
    - 19.8.4
    - 19.8.5
    - 19.8.9
    - 19.9.1
    - 19.9.2
    - 20.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.23.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.8
    - 24.3.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.16
    - 7.12.17
    - 7.13.10
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.16
    - 7.12.17
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@types/react-select"
    versions:
    - 3.1.2
    - 4.0.11
  - dependency-name: react-table
    versions:
    - 7.6.3
  - dependency-name: bl
    versions:
    - 4.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  rebase-strategy: disabled
  registries:
  - npm-registry-npm-pkg-github-com
