version: 2
jobs:
  website_release:
    docker:
    - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: git checkout gh-pages
    - run: npm install
    - run: npm run build:storybook
    - run: git add storybook-static/ && git commit --allow-empty -m "Update static website"
    - run: git push origin gh-pages

  deploy:
    docker:
    - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    # Update package.json version
    - run: npm version v$CIRCLE_TAG
    - run: git push origin master
    # Update installs
    - run: npm install
    # Update the npm package
    - run: npm run build:storybook
    - run: npm run build:package
    - run: echo '//registry.npmjs.org/:_authToken=${npm_TOKEN}' > ~/repo/.npmrc
    - run: cd ./build
    - run: npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - website_release
    - deploy
