version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: npm run build:static
      - run: npm test
      - run: npm run linter:check
      - run: npm run build:package
      # preview what files will be packaged into npm
      - run: ls ./dist

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  release:
    docker:
      - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Update package.json version
      - run: npm version $CIRCLE_TAG && git push origin HEAD:master
      - run: npm install
      # Deploys static website of storybook.
      - run: npm run build:storybook
      # Builds package.
      - run: npm run build:package
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/repo/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
