version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install
    - run: npm run linter:check
    - run: npm run build:package
    - run: npm run build:storybook
    # preview what files will be packaged into npm
    - run: ls ./build

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
    - image: circleci/node:8.11.1

    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    # Update package.json version
    - run: npm version $CIRCLE_TAG
    - run: git push origin master
    - run: npm install
    # Deploys static website of storybook.
    - run: npm run build:storybook
    # Builds package.
    - run: npm run build:package
    - run: echo '//registry.npmjs.org/:_authToken=${npm_TOKEN}' > ~/repo/.npmrc
    - run: npm publish ./dist --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - master
    - deploy:
        filters:
          tags:
            only: /.*/
        branches:
          ignore: /.*/
