version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9.0-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm run build:static
      - run: npm run linter:check
      - run: npm test
      - run: npm run danger
      - run: npm run build:package
      # preview what files will be packaged into npm
      - run: ls ./dist

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Allow us to see failed storyshot diff files in the circle CI artifacts UI
      - store_artifacts:
          path: ~/repo/tests/__image_snapshots__/__diff_output__
          destination: storyshot-diffs

  pr-preview:
    docker:
      - image: circleci/node:11.9.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Deploys static website of storybook.
      - run:
          name: "What branch am I on?"
          command: echo "$CIRCLE_BRANCH/bin:$CIRCLE_BRANCH"
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_PROJECT_REPONAME}
      - run:
          name: "What branch am I on?"
          command: echo ${GITHUB_REPO_ACCESS}
      - run:
          name: "What branch am I on?"
          command:  echo ${REPONAME}
      - run:
          name: "CIRCLE?"
          command: echo ${CIRCLE_SHA1}
      - run:
          name: "What CIRCLE_PULL_REQUEST?"
          command: echo ${CIRCLE_PULL_REQUEST}
      - run:
           name: deploy preview in actual url
           command: |
            echo ${CIRCLE_SHA1}-${CIRCLE_PROJECT_REPONAME}.surge.sh
            curl -H Authorization: token ${GITHUB_REPO_ACCESS} --request POST https://api.github.com/repos/VivyTeam/${CIRCLE_PROJECT_REPONAME}/statuses/${CIRCLE_SHA1} --data  '{ "state" : "success", "target_url": "${CIRCLE_SHA1}-${CIRCLE_PROJECT_REPONAME}.surge.sh", "context": "${CIRCLE_PROJECT_REPONAME}", "description": "Preview for PR deployed!" }'
      - run:
          name: PR Preview Storybook
          command: |
            npm install
            npm run build:static
            mv .out .public
            yarn run surge --project .public --domain ${CIRCLE_SHA1}-${CIRCLE_PROJECT_REPONAME}.surge.sh

  release:
    docker:
      - image: circleci/node:11.9.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Update package.json version
      - run: npm version $CIRCLE_TAG && git push origin HEAD:master
      - run: npm install
      # Deploys static website of storybook.
      - run: npm run build:storybook
      # Builds package.
      - run: npm run build:package
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/repo/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - pr-preview:
          filters:
            branches:
              ignore:
                - master
      - build:
          filters:
            branches:
              ignore:
                - master
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
