/// <reference types="Cypress" />

context("Visual Regression - Vivy", () => {
  beforeEach(() => {
    cy.eyesOpen({
      appName: "Vivy Components",
      testName: "Visual Regression - Vivy",
      browser: [
        {
          name: "chrome",
          width: 1280,
          height: 800
        },
        {
          name: "firefox",
          width: 1280,
          height: 800
        }
      ]
    });
  });

  afterEach(() => {
    cy.eyesClose();
  });

  const ids = [
    "welcome",
    "welcome--principles",
    "welcome--vision-ethos",
    "welcome--typography",
    "welcome--color-palette",
    "welcome--logos",
    "alert",
    "alert--success",
    "alert--warning",
    "alert--without-success-icon",
    "alert--without-warning-icon",
    "alertsmall",
    "alertsmall--success",
    "alertsmall--warning",
    "alertsmall--without-success-icon",
    "alertsmall--without-warning-icon",
    "anchorbutton",
    "anchorbutton--primary",
    "anchorbutton--primary-with-height-large",
    "anchorbutton--primary-with-height-small",
    "anchorbutton--primary-with-custom-width",
    "anchorbutton--secondary",
    "anchorbutton--secondary-with-height-large",
    "anchorbutton--secondary-with-height-small",
    "anchorbutton--secondary-with-custom-width",
    "anchorbutton--with-an-icon",
    "button",
    "button--primary",
    "button--primary-height-large",
    "button--primary-with-height-small",
    "button--primary-with-custom-width",
    "button--primary-disabled",
    "button--secondary",
    "button--secondary-with-height-large",
    "button--secondary-with-height-small",
    "button--secondary-with-custom-width",
    "button--secondary-disabled",
    "button--with-an-icon",
    "button--onclick-handler",
    "caption",
    "caption--basic",
    "caption--styled",
    "caption--type-bold",
    "checkbox",
    "checkbox--basic",
    "checkbox--optional",
    "datedisplay",
    "datedisplay--basic",
    "datedisplayminimal",
    "datedisplayminimal--basic",
    "display",
    "display--basic",
    "display--styled",
    "form",
    "form--documentation",
    "form--without-validation",
    "form--with-validation",
    "form--inactive-validation-on-value-change",
    "form--inactive-validation-on-value-change-and-on-blur",
    "grid",
    "grid--default-width",
    "grid--full-width",
    "grid--responsive-column-sizes",
    "grid--hidden-column-only-on-small-devices",
    "grid--space-around",
    "grid--space-evenly",
    "grid--space-between",
    "grid--position-start",
    "grid--position-center",
    "grid--position-end",
    "grid--responsive-position-end",
    "grid--offset",
    "grid--vertical-alignment-top",
    "grid--vertical-alignment-middle",
    "grid--vertical-alignment-bottom",
    "grid--complex-vertical-alignment-example",
    "grid--columns-in-reverse-order",
    "grid--column",
    "grid--text-align-is-on-left",
    "grid--text-align-is-on-center",
    "grid--text-align-is-on-right",
    "grid--responsive-text-align-is-on-right",
    "grid--nested-rows",
    "h1",
    "h1--basic",
    "h1--styled",
    "h2",
    "h2--basic",
    "h2--styled",
    "icon",
    "icon--basic",
    "icon--vivy-font-icon-pack",
    "input",
    "input--basic",
    "input--default-value",
    "input--onchange-handler",
    "input--onblur-handler",
    "input--icon-left",
    "input--with-focus-on-click",
    "inputmasked",
    "inputmasked--basic",
    "inputmasked--with-placeholdermask",
    "inputmasked--with-defaultvalue",
    "inputmasked--with-focus-on-click",
    "inputpassword",
    "inputpassword--icon-left",
    "inputpassword--with-visibility-property-true",
    "inputpassword--with-visibility-and-showpassword-properties-true",
    "layout",
    "layout--simple-page",
    "medicalcard",
    "medicalcard--basic",
    "modal",
    "modal--basic",
    "modal--only-submit-button",
    "modal--only-cancel-button",
    "modal--both-cancel-and-submit-buttons",
    "modal--with-long-content",
    "modal--modal-size-small",
    "modal--with-page-that-has-more-height-than-one-screen",
    "modal--toggle-availability-of-submit-button",
    "notfoundpage",
    "notfoundpage--basic",
    "notify",
    "notify--documentation",
    "notify--basic-notification",
    "paragraph",
    "paragraph--basic",
    "paragraph--styled",
    "paragraph--type-bold",
    "select",
    "select--basic",
    "select--with-options",
    "select--with-onchange-func",
    "sidebar",
    "sidebar--basic",
    "simpleloader",
    "simpleloader--basic",
    "simpleloader--centered",
    "simpleloader--loader-with-custom-size",
    "table",
    "table--basic",
    "table--auto-sizing-column-widths",
    "table--custom-cell-contents",
    "table--no-data",
    "textarea",
    "textarea--basic",
    "textarea--disabled",
    "textarea--required",
    "textarea--with-style",
    "tiny",
    "tiny--basic",
    "tiny--styled",
    "tiny--type-bold",
    "topbar",
    "topbar--basic",
    "vivyfooter",
    "vivyfooter--default-styles"
  ];

  ids.forEach(id => {
    it(`Should click on '${id} page'`, () => {
      cy.visit(`/${id}`);
      cy.get(`#explorer${id}`).trigger("mousedown");
    });
  });
});
